### PR TITLE
fix: don't start operator if `last_processed_batch_filepath` isn't provided

### LINKED ISSUE #1209: Don't start operator if it hasn't provide `last_processed_batch_filepath` in config file
Currently there is no check if the `last_processed_batch_filepath` field has been provided in the config file. Since this is a new mandatory field, we need to make sure we do a fatal log to ensure all operators set this field.

### PR DESCRIPTION
**Pull request by MarcosNicolau**
**Changes**
If `last_processed_batch_filepath` is not provided on the operator config, then don't start the program. This is to make sure operator owners don't forget to pass this new field. Alternatively, we could create a default file but I am not sure about how that could go.

**Testing**
Remove the `last_processed_batch_filepath` from the operator config and you should see an err indicating the missing field.

Closes #1209

### CODE REVIEW

**Review by JuArce — APPROVED** [review]

**Comment by PatStiles** [comment]
Works on my machine

**Review by PatStiles — APPROVED** [review]

**Review by uri-99 — CHANGES_REQUESTED** [review]
It should also fail if the folder of the file is non-existent. This is because Operator will fail to create the file if the folder given does not exist.

**Comment by MarcosNicolau** [comment]
> It should also fail if the folder of the file is non-existent. This is because Operator will fail to create the file if the folder given does not exist.

Updated!

**Review by uri-99 — CHANGES_REQUESTED** [review]
new constraint doesnt allow creation of file. It should be able to create a file, but only on an existing directory.

**Review by uri-99 — APPROVED** [review]

**Pull request merged**
