### PR TITLE
feat: add infinite sp1 for testnet

### LINKED ISSUE #259: feat: add infinite sp1 for testnet

### PR DESCRIPTION
**Pull request by NicolasRampoldi**
# Description

- To test, make sure you have python3 installed.
- Go to `/batcher/client/send_infinite_sp1_tasks` and run `pip install -r requirements.txt`.
- Then run `make batcher_send_infinite_sp1`

### CODE REVIEW

**Review by jotabulacios — APPROVED** [review]
lgtm

**Comment by taturosati** [comment]
I think https://github.com/yetanotherco/aligned_layer/pull/280 should be merged first, then call to batcher client should be with the installed version, since it recompiles ~6 crates each time it runs because of warning:

```
warning: skipping duplicate package `fibonacci-program`
```

**Comment by NicolasRampoldi** [comment]
> I think #280 should be merged first, then call to batcher client should be with the installed version, since it recompiles ~6 crates each time it runs because of warning:
> 
> ```
> warning: skipping duplicate package `fibonacci-program`
> ```

Done 🫡

**Review by taturosati — APPROVED** [review]
lgtm

**Pull request merged**
