### PR TITLE
fix: update anvil state and version

### PR DESCRIPTION
**Pull request by samoht9277**
# Fixes broken `anvil` state

## Description
This minor PR fixes the deployed anvil states which broke the CI

```
contracts/scripts/anvil/state/alignedlayer-deployed-anvil-state.json
contracts/scripts/anvil/state/eigenlayer-deployed-anvil-state.json
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

**Review by uri-99 — APPROVED** [review]
CI seems to pass correctly

**Review by IAvecilla — APPROVED** [review]

**Comment by Oppen** [comment]
The CI seems stuck waiting for the runner.

**Review by uri-99 — CHANGES_REQUESTED** [review]
WIP discussing if this change is necesarry

**Review by uri-99 — APPROVED** [review]
new foundry version breaks old anvil states, this anvil_state regeneration is needed

**Review by Oppen — APPROVED** [review]

**Review by Oppen — APPROVED** [review]

**Pull request merged**
