### PR TITLE
chore(security): Bump gnark version

### LINKED ISSUE #967: bump gnark version to v0.11

### PR DESCRIPTION
**Pull request by PatStiles**
Bumps the gnark version from v.0.11.0 -> v.0.14.0 to address security concerns outlined by the gnark team [here](https://www.zellic.io/blog/gnark-bug-groth16-commitments/). Closes #967

### CODE REVIEW

**Review by entropidelic — CHANGES_REQUESTED** [review]
when testing, Go projects don't build. It seems there has been some API changes
```bash
make aggregator_start
Starting Aggregator...
# github.com/crate-crypto/go-kzg-4844/internal/kzg
../go/pkg/mod/github.com/crate-crypto/go-kzg-4844@v1.0.0/internal/kzg/kzg_verify.go:73:20: claimedValueG1Jac.ScalarMultiplicationAffine undefined (type bls12381.G1Jac has no field or method ScalarMultiplicationAffine)%
```

**Comment by PatStiles** [comment]
`go-kzg-4844` and `c-kzg-4844` were updated to accommodate the changes with the gnark library.

**Comment by PatStiles** [comment]
@entropidelic re-importing the gnark packages in the batcher resolved the verification error on my end.

**Comment by entropidelic** [comment]
after running `go clean` in the root folder, `cargo clean` in the batcher folder, and re-building everything, it worked

**Review by entropidelic — APPROVED** [review]

**Comment by MauroToscano** [comment]
We should specify the new supported gnark version on the docs

**Comment by PatStiles** [comment]
@MauroToscano Docs updated

**Review by uri-99 — APPROVED** [review]

**Pull request merged**
