### PR TITLE
feat: integrate lita verifier

### LINKED ISSUE #1154: Integrate Lita verifier, add it to docs
https://github.com/lita-xyz

### PR DESCRIPTION
**Pull request by MarcosNicolau**
**Changes**
Adds lita verifier.

**Testing**
To test it, setup an aligned devnet as usual and run the following commands: 
1. `make build_valida_linux`
2. `make test_valida_rust_ffi`
3. `make test_valida_go_bindings_linux`
4. `make batcher_send_valida_burst`

**NOTE:** Lita is only supported on Linux. Tests will fail in `macos` devices.

Closes #1154

### CODE REVIEW

**Comment by Oppen** [comment]
@MarcosNicolau can you point me to some docs so I can double check the code matches the protocol?

**Comment by MarcosNicolau** [comment]
@Oppen, sure here is the reference:
- [lita docs](https://lita.gitbook.io/lita-documentation)
- [lita release I am using](https://github.com/lita-xyz/llvm-valida-releases/releases/tag/v0.1.0-alpha)
- [lita valida vm](https://github.com/valida-xyz/valida)

**Comment by Oppen** [comment]
Converted to draft due to not being a priority for mainnet

**Comment by JuArce** [comment]
Stale

**Pull request closed without merging**
