### PR TITLE
feat(audit): Remove use of storage gaps in upgradeable contracts

### LINKED ISSUE #1068: Usage of storage gaps in upgradeable contracts (INFORMATIONAL)
- [ ] Remove  __GAP variable from both the BatcherPaymentService and AlignedLayerServiceManager contracts, This is due to these contracts not being inherited by any other contracts, and therefore the __GAP variable serves no purpose
- [ ] Update all of the __GAP variables to be of size 50, and adhere tothe above described process for decrementing this during future upgrades. Second, we

### PR DESCRIPTION
**Pull request by PatStiles**
closes: #1068 

To Test:
- [x] Run Local Testnet with deployed contracts by first running `anvil_deploy_aligned_contract` before `anvil_start_with_block_time`
- [x] Re run Local testnet and ensure nothing breaks
- [x] Upgrade the contracts by running `anvil_upgrade_aligned_contracts` & `anvil_upgrade_batcher_payment_service`

### CODE REVIEW

**Review by uri-99 — CHANGES_REQUESTED** [review]
The issue of this PR says we do not inherit these contracts. This is not true, each storage is inherited by its implementation. Is it possible this issue is deprecated? @MauroToscano

**Comment by uri-99** [comment]
Closing as issue is deprecated

**Comment by MauroToscano** [comment]
Issue is not deprectaed

**Comment by MauroToscano** [comment]
Closing

**Pull request closed without merging**
