### PR TITLE
fix(telemetry): remove sensitive data exposure

### PR DESCRIPTION
**Pull request by avilagaston9**
# Telemetry: remove sensitive data exposure

## Description

Changes the `/versions` endpoint to only expose the following fields of the operator:

- operator_id
- name
- version
- address
- stake

## How to Test

1. Start anvil:

```bash
make anvil_start_with_block_time
```

2. Start telemetry:

```bash
make telemetry_clean_db
make telemetry_full_start
```

3. Start aggregator:

```bash
make aggregator_start
```

4. Register and start an operator:

```bash
make operator_register_and_start
```

5. Go to `localhost:4001/versions` and check that the displayed data is the expected.

6. Also check the endpoint for that specific operator in `localhost:4001/versions/{operator_address}`.

7. Finally, check that `localhost:4001/api/operators` and `localhost:4001/api/operators/{operator_address}` keeps displaying all operator data, not just the public.

> [!NOTE]
> The version may appear with a `null` value. This is because the `version` variable in the operator is set in compile time and we are not running the operator compiled binary.

## Type of change

- [x] Bug fix

## Checklist

- [x] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

**Review by MarcosNicolau — APPROVED** [review]
LGTM

**Review by uri-99 — COMMENTED** [review]
I'm missing the information of version and rpc, but may be a local issue

**Comment by PatStiles** [comment]
Ran locally and saw the described information.

**Review by PatStiles — APPROVED** [review]

**Review by JuArce — APPROVED** [review]

**Comment by JulianVentura** [comment]
> I'm missing the information of version and rpc, but may be a local issue

This may happen if the operator is started before the telemetry service is on, since said information is provided at operator startup on `SendTelemetryData` function. Please, check if restarting the operator solves the problem

**Review by JulianVentura — APPROVED** [review]
Code looks good and it worked as expected locally

**Pull request merged**
