### PR TITLE
feat: add operator responses dashboard

### PR DESCRIPTION
**Pull request by avilagaston9**
# Add Operator Responses Dashboard

## Description

This PR adds a new Grafana dashboard with the count of the operators responses received in the selected time range:

image

## How to test

You can follow similar steps as #1621 to test the full flow of this PR.

## Type of change

- [x] New feature

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

**Review by PatStiles — APPROVED** [review]
Tested locally and everything works!

**Review by MarcosNicolau — APPROVED** [review]
Works nicely! Question: doesn't this metric make the one from #1621 redundant? Since this metric shows the number of responded tasks and the total tasks, the difference in responded tasks can be derived (this could be done via Grafana). Also, this metric updates in real time, whereas the one in #1621 updates only when quorum is reached.

**Review by JuArce — CHANGES_REQUESTED** [review]
- Sort the values by lower responding operators first
- Show a single color without gradient

**Comment by avilagaston9** [comment]
> - Sort the values by lower responding operators first
> - Show a single color without gradient
> @JuArce 

Addressed both using a table + override with a gauge display. I had to use the "RETRO LCD" display because with the basic one, the progress bar appears empty when all values are the same:

image

image

**Review by JuArce — APPROVED** [review]

**Pull request merged**
