### PR TITLE
feat(aggregator): add check for Tx inclusion for Aggregated Responses in case of Re-orgs

### PR DESCRIPTION
**Pull request by PatStiles**
After a successful tx is sent by the aggregator to the contract check the aggregator waits 30 sec before confirming the Tx receipt is included in case of a re-org.

### CODE REVIEW

**Comment by MauroToscano** [comment]
Don't error, go back at retrying

**Comment by PatStiles** [comment]
Done!

**Review by MauroToscano — COMMENTED** [review]
Code seems alright. Give it two tests before merging

**Review by taturosati — COMMENTED** [review]
Code looks good

**Comment by MauroToscano** [comment]
Stale

**Pull request closed without merging**
