### PR TITLE
feat: operator liveness metric

### PR DESCRIPTION
**Pull request by avilagaston9**
# Operator Liveness Metric

## Motivation

We need a way to rapidly determine if an operator is down.

## Description

Adds a Bar Gauge with the count of missed tasks for each operator over a specified time range.

image

## How To Test

1. Start anvil:
```bash
make anvil_start_with_block_time
```
2. Start the telemetry server in interactive mode:
```bash
make telemetry_run_db
make telemetry_ecto_migrate
cd telemetry_api
ALIGNED_CONFIG_FILE="../contracts/script/output/devnet/alignedlayer_deployment_output.json" OPERATOR_FETCHER_WAIT_TIME_MS=5000 ENVIRONMENT=devnet RPC_URL=http://localhost:8545 iex -S mix phx.server
```
3. Run metrics:
```bash
make run_metrics
```
4. Initialize different operator names from the telemetry terminal:
```Elixir
TelemetryApi.PrometheusMetrics.initialize_operator_metrics("gaston")
```
4. Call the `missing_operator` method from the telemetry terminal with the initialized operator names:
```Elixir
TelemetryApi.PrometheusMetrics.missing_operator("gaston")
```
6. Go to the aggregator-batcher dashboard in `localhost:3000` and you should see the dashboard with the values.

### Test also the full flow:
1. Start anvil:
```bash
make anvil_start_with_block_time
```
2. Start batcher:
```bash
make batcher_start_local
```
3. Go to `config-files/config-aggregator.yaml` and reduce the `bls_service_task_timeout`.
4. Start the aggregator:
```bash
make aggregator_start
```
7. Register and start the operator:
```bash
make operator_register_and_start
```
8. Send tasks:
```bash
make batcher_send_burst_groth16
```

9. Kill the operator and watch the panel.

## Type of change

- [x] New feature

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

**Comment by uri-99** [comment]
WIP discussing the possibility of a graph

**Comment by Oppen** [comment]
> WIP discussing the possibility of a graph

Given we need the metric, wouldn't it be better to merge and change later to improve its display?

**Comment by avilagaston9** [comment]
> Given we need the metric, wouldn't it be better to merge and change later to improve its display?

I agree with this. I don't know how much information an historical graph will add.

**Review by uri-99 — APPROVED** [review]

**Review by PatStiles — APPROVED** [review]

**Review by MarcosNicolau — APPROVED** [review]
Works locally!

**Review by JulianVentura — APPROVED** [review]

**Comment by Oppen** [comment]
The metrics doesn't seem to update locally. The manual triggers work, but killing my real operator doesn't make the metric go up:
image
image

Maybe some instruction is missing?

It also seems like the metric clears itself after some time, I guess that's normal?
image

**Comment by avilagaston9** [comment]
> The metrics doesn't seem to update locally. The manual triggers work, but killing my real operator doesn't make the metric go up:
> @Oppen 

I was missing the step to send proofs, but from the picture you send it looks like you are already doing that. I followed the steps again an it worked in my machine 🤔.

> It also seems like the metric clears itself after some time, I guess that's normal?

Yes, the metric is configured to show only the missed responses in the selected time range on the top-right corner:

image

**Review by Oppen — APPROVED** [review]
Worked after ~~solving the skill issue~~ shortening ttl for tasks.

**Review by JuArce — CHANGES_REQUESTED** [review]
- Remove the "total" transformation in grafana dashboard
- Sort the values by higher not responding operators first

**Comment by avilagaston9** [comment]
@JuArce

I added the total transformation since when only one operator was missing tasks, no name was displayed on the bar gauge:

image


Also, the bar gauge lacked an option to dynamically order the labels.

I addressed both in [#15a53ae](https://github.com/yetanotherco/aligned_layer/pull/1621/commits/15a53ae9ef60afd1e8d5124d485bde5ceb08f804) by switching from a "Bar Gauge" to a simple "table + gauge display" with successful results:

image

**Review by JuArce — APPROVED** [review]

**Pull request merged**
